### ISSUE TITLE
Selecting from a MultiIndex column returns a series but should be a DataFrame

### ISSUE THREAD

**Issue by cfaaron** [fireducks-dev/fireducks#32]
Hello,

When running code such as ```df['col']``` where DF is a DataFrame with a MultiIndex column, it appears that fireducks treats the return result as a series, but pandas returns a DataFrame.

fireducks==1.1.1
pandas==2.2.3

main_fireducks_debug.py
```
import numpy as np
import pandas as pd
import fireducks.pandas as fd


def make_data(data_frame):
    columns = pd.MultiIndex.from_product([['a', 'b'], ['c', 'd', 'e', 'f']])
    index = pd.RangeIndex(500)
    rng = np.random.default_rng(42)
    arr = rng.normal(size=(len(index), len(columns)))
    df = data_frame(arr, index=index, columns=columns)
    return df


def main():
    print('PANDAS')
    data_pd = make_data(pd.DataFrame)
    data_pd_a = data_pd['a']
    print(type(data_pd_a))
    pd_mean_0 = data_pd_a.mean()
    print(pd_mean_0)
    pd_mean_1 = data_pd_a.mean(axis=1)
    print(pd_mean_1)
    print()

    print('FIREDUCKS')
    data_fd = make_data(fd.DataFrame)
    data_fd_a = data_fd['a']
    print(type(data_fd_a))
    fd_mean_0 = data_fd_a.mean()
    print(fd_mean_0)
    fd_mean_1 = data_fd_a.mean(axis=1)
    print(fd_mean_1)
    print()



if __name__ == '__main__':
    main()
```

Output:
```
PANDAS
<class 'pandas.core.frame.DataFrame'>
c   -0.026696
d   -0.003747
e   -0.039236
f   -0.009741
dtype: float64
0      0.238937
1      0.196836
2      0.059598
3      0.029323
4      0.104734
         ...
495    0.677913
496   -0.749269
497    0.394609
498   -0.527993
499   -0.268036
Length: 500, dtype: float64

FIREDUCKS
<class 'fireducks.pandas.series.Series'>
-0.026695968043714217
Traceback (most recent call last):
  File "/home/aaron/code/sig_gen/src/main_fireducks_debug.py", line 39, in <module>
    main()
  File "/home/aaron/code/sig_gen/src/main_fireducks_debug.py", line 32, in main
    fd_mean_1 = data_fd_a.mean(axis=1)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaron/code/sig_gen/venv312/lib/python3.12/site-packages/fireducks/pandas/generic.py", line 294, in wrapper
    return _func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaron/code/sig_gen/venv312/lib/python3.12/site-packages/fireducks/pandas/generic.py", line 1547, in mean
    return self._build_aggregation_op("mean", *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaron/code/sig_gen/venv312/lib/python3.12/site-packages/fireducks/pandas/generic.py", line 1495, in _build_aggregation_op
    return self._fallback_call(op, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaron/code/sig_gen/venv312/lib/python3.12/site-packages/fireducks/pandas/generic.py", line 359, in _fallback_call
    return utils.fallback_call_packed(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaron/code/sig_gen/venv312/lib/python3.12/site-packages/fireducks/pandas/utils.py", line 285, in fallback_call_packed
    return ff.fallback_call(
           ^^^^^^^^^^^^^^^^^
  File "/home/aaron/code/sig_gen/venv312/lib/python3.12/site-packages/fireducks/fallback.py", line 207, in fallback_call
    method = fallback_attr(
             ^^^^^^^^^^^^^^
  File "/home/aaron/code/sig_gen/venv312/lib/python3.12/site-packages/fireducks/fallback.py", line 127, in fallback_attr
    obj = fallbacker(reason=reason)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaron/code/sig_gen/venv312/lib/python3.12/site-packages/fireducks/pandas/generic.py", line 343, in _unwrap
    return self.to_pandas(reason=f"unwrap ({reason})")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaron/code/sig_gen/venv312/lib/python3.12/site-packages/fireducks/pandas/generic.py", line 1360, in to_pandas
    self._fireducks_meta.set_cache(self._to_pandas(options=options))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaron/code/sig_gen/venv312/lib/python3.12/site-packages/fireducks/pandas/series.py", line 766, in _to_pandas
    isinstance(result, pandas.DataFrame)
AssertionError: <class 'pandas.core.frame.DataFrame'>[4] is not pandas.Series
```

**Comment by qsourav** [comment]
Thank you so much for reporting the bug. We will fix it soon.

Best Regards,
Sourav Saha

**Comment by k-ishizaka** [comment]
Thank you for reporting the issue. 

This particular case has been fixed in fireducks-1.1.6. But because it is not an easy task for fireducks which uses lazy execution model to decide correct data type, i.e. DataFrame or Series, depending on a result of selection, more complex cases could still have the same problem.
